name: opo-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.12.3
  - numpy=1.26.4
  - matplotlib
  - pip:
    - gymnasium==0.29.1
    - pygame==2.5.2
    - pytest==8.1.2
